import os
from netmiko import ConnectHandler
from getpass import getpass
from netmiko.ssh_exception import AuthenticationException

USERNAME = input("Please enter your SSH username: ")
Pass = getpass("Please enter your SSH password: ")

device = {
  'ip' : '192.168.108.12',
  'username' : USERNAME,
  'password' : PASS,
  'device_type' : 'cisco_iso'
}

try:
  c = ConnectHandler(**device)
  output = c.send_command('show run')
  f.write(output)
  f.close()

except (AuthenticationException):
  print("An authentication error occured while connection to: " + device['ip'])

# netmiko.ssh_exception is not working
